#! /usr/bin/perl
# Not -T because we probably need to use the PERL5LIB

use strict;
use warnings;

use Test::HTtapTP;
use Test::More;

sub main {
    plan tests => 3;

    my $name = $ENV{HTTP_X_HTTAPTP_NAME} || '';  # XXX: non-API
    diag "name = $name";

    ok(5, "five");
    is(2+2, 4, "2+2=");
    isnt($name, "plain fail", "did the caller want a fail?");

    warn "hmm?\nit must be a <b>warning</b>";
    if ($name eq 'snore') {
        sleep 5; # timeout = 3s
    } elsif ($name eq 'b0rk') {
        die "This one is broken - after the passes";
    } # else, whatever

    diag explain \%ENV;
}

exit main();
