#! /usr/bin/perl -T
use strict;
use warnings;

use Test::HTtapTP;
use Test::More;

sub main {
    plan tests => 2;
    my $name = $ENV{HTTP_X_HTTAPTP_NAME};
    diag "name = $name";
    ok(5, "five");
    is(2+2, 4, "2+2=");
    warn "hmm?\nit must be a <b>warning</b>";
sleep 35 if $name eq 'snore';
    die "This one is broken" if $name eq 'b0rk'; # XXX: non-API
    diag explain \%ENV;
}

exit main();
